### ISSUE TITLE
Response: Invalid value '>= 6' for metadata.platforms

### ISSUE THREAD

**Issue by GMartinez-Sisti** [karnauskas/chef-yum-plugin-versionlock#10]
Hi,

I'm using Chef Server 12.7.2-1 in Ubuntu and I found that a change broke the cookbook for me.

I'm seeing this error when trying to upload the cookbook v0.1.2:

`Uploading yum-plugin-versionlock [0.2.0]`
`ERROR: The data in your request was invalid`
`Response: Invalid value '>= 6' for metadata.platforms`

It looks like the issue is being caused by the lines:

- https://github.com/karnauskas/chef-yum-plugin-versionlock/blob/master/metadata.rb#L15
`supports 'redhat', '>= 6'`
- https://github.com/karnauskas/chef-yum-plugin-versionlock/blob/master/metadata.rb#L16
`supports 'centos', '>= 6'`

Please let me know if I can help with something else.

Regards

**Comment by karnauskas** [comment]
That's interesting. How to reproduce this? What version for `knife` do you use? I used foodcritic to validate this, looked alright.

**Comment by GMartinez-Sisti** [comment]
I'm using:

- Windows 10 1703 build 15063.608 (I know, I know...)
- Chef SDK 1.2.22
- Knife says:  `knife help -v`
`Chef: 12.18.31`

**Comment by karnauskas** [comment]
Chef Server looks a bit outdated, tho I have no idea if there're any incompatible changes.

**Comment by GMartinez-Sisti** [comment]
I'll try to update the Chef SDK, and let you know. Might take a couple of days.

Thanks

**Comment by karnauskas** [comment]
I was able to see same problem, fixed for now.
