### ISSUE TITLE
Running on chef kitchen shows No candidate version available for yum-plugin-versionlock

### ISSUE THREAD

**Issue by mesgme** [karnauskas/chef-yum-plugin-versionlock#13]

**Comment by mesgme** [comment]
I see this issue when running on various rhel vagrant boxes on top of windows.  Works fine for centos bento box.

thussain/rhel7
iamseth/rhel-6.8-x86_64

**Comment by erinn** [comment]
Make sure your systems are subscribed yum-plugin-versionlock is provided by RHEL and only available after the subscription-manager has been run and the system entitled.

**Comment by karnauskas** [comment]
I can't do anything if package is not in repository. I can't verify if it's there or under different name.
