### ISSUE TITLE
Chef 17 / `unified_mode`-compliant release

### ISSUE THREAD

**Issue by detjensrobert** [karnauskas/chef-yum-plugin-versionlock#63]
The currently-released version of this cookbook on the supermarket (`v0.4.0`) is currently causing some deprecation warnings for `unified_mode`. These were fixed in [f882e3c](https://github.com/karnauskas/chef-yum-plugin-versionlock/commit/f882e3c99675f20f101d64ed65a4acba536a2312) but there has not been a release since then.

Could you please cut a release including the `unified_mode` fix?

Thanks!

**Comment by karnauskas** [comment]
I have pushed this as v0.4.1 to supermarket, hope this fix deprecation warnings.
